name: Tests
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
        php-versions: [7.2, 7.3, 7.4]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}        
          extensions: mbstring
          ini-values: pcov.directory=api
          coverage: pcov
      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist
      - name: Test with phpunit
        run: vendor/bin/phpunit --coverage-clover build/logs/clover.xml --coverage-text
      - name: coveralls
        run: sh -c php vendor/bin/php-coveralls -v
      - name: codecov-umbrella
        run: curl -s https://codecov.io/bash | bash -s -- -t ${{secrets.CODECOV_TOKEN}} -f build/logs/clover.xml -n github-actions-codecov
